name: Generate SBOMs (ubuntu 26.04 test)
'on':
  workflow_call: null
  workflow_dispatch: null
env:
  REGISTRY: ghcr.io
jobs:
  generate-sbom:
    runs-on: ubuntu-26-amd64
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Download Syft
      uses: anchore/sbom-action/download-syft@8d0a6505bf28ced3e85154d13dc6af83299e13f1
    - name: Create source SBOM
      run: syft dir:. --output spdx-json=feldera-sbom-source-c99b0355cc8f458cabaf634d2a3e8ff1ee89ce2f.spdx.json
    - name: Login to GHCR
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create image SBOM
      run: |
        IMAGE_REF=${{ vars.FELDERA_IMAGE_NAME }}:sha-c99b0355cc8f458cabaf634d2a3e8ff1ee89ce2f
        syft "$IMAGE_REF" --output spdx-json=feldera-sbom-image-c99b0355cc8f458cabaf634d2a3e8ff1ee89ce2f.spdx.json
    - name: Upload SBOM artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: feldera-sbom
        path: |
          feldera-sbom-source-c99b0355cc8f458cabaf634d2a3e8ff1ee89ce2f.spdx.json
          feldera-sbom-image-c99b0355cc8f458cabaf634d2a3e8ff1ee89ce2f.spdx.json
        retention-days: 7
