name: Adapter Tests (ubuntu 26.04 test)
'on':
  workflow_call: null
  workflow_dispatch:
    inputs:
      run_id:
        description: ID of the workflow run that uploaded the artifact
        required: true
permissions:
  actions: read
  contents: read
  id-token: write
jobs:
  adapter-tests-pubsub:
    name: Test Adapters (PubSub only)
    runs-on: ubuntu-26-amd64
    container:
      image: ghcr.io/feldera/feldera-dev:sha-6f8e388fcd3b56c72a9305f108ae43dd07e3897e
    services:
      pubsub:
        image: ghcr.io/feldera/gcloud-pubsub-emulator:e852273e07
        ports:
        - 8681:8681
        options: -e PUBSUB_PROJECT1=feldera-test,test_pubsub_input-0 --health-cmd "nc -z 127.0.0.1 8681" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Download Test Binaries
      uses: ./.github/actions/download-artifact-retry
      with:
        name: feldera-test-binaries-x86_64-unknown-linux-gnu
        path: build
        run-id: ${{ github.event.inputs.run_id || github.run_id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Make binaries executable
      run: chmod +x ./build/*
    - name: Run adapters pubsub tests
      if: ${{ vars.CI_DRY_RUN != 'true' }}
      run: ../../build/dbsp_adapters-* pubsub
      working-directory: crates/adapters
      env:
        RUST_BACKTRACE: 1
        PUBSUB_EMULATOR_HOST: pubsub:8681
